name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: docker://jekyll/builder
    - name: Install dependencies
      run: npm install
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: '3.0'
    # - name: Install dependencies
    #   run: bundle install
    # - name: Install jekyll-pagebreak
    #   run: gem install jekyll-pagebreak
    - name: Build Jekyll site
      run: npm run install-jekyll
    # - name: ðŸ”¨ install dependencies & build site
    #   uses: limjh16/jekyll-action-ts@v2
    #   with:
    #     enable_cache: true
    #     ### Enables caching. Similar to https://github.com/actions/cache.
    #     #
    #     # format_output: true
    #     ### Uses prettier https://prettier.io to format jekyll output HTML.
    #     ### To disable, just leave this commented out, prettier is disabled by default. https://github.com/limjh16/jekyll-action-ts/issues/12
    #     #
    #     # prettier_opts: '{ "useTabs": true }'
    #     ### Sets prettier options (in JSON) to format output HTML. For example, output tabs over spaces.
    #     ### Possible options are outlined in https://prettier.io/docs/en/options.html
    #     #
    #     # prettier_ignore: 'about/*'
    #     ### Ignore paths for prettier to not format those html files.
    #     ### Useful if the file is exceptionally large, so formatting it takes a while.
    #     ### Also useful if HTML compression is enabled for that file / formatting messes it up.
    #     #
    #     # jekyll_src: sample_site
    #     ### If the jekyll website source is not in root, specify the directory. (in this case, sample_site)
    #     ### By default, this is not required as the action searches for a _config.yml automatically.
    #     #
    #     # jekyll_env: development
    #     ### If you need to specify `JEKYLL_ENV` environment variable or `jekyll.environment` Liquid variable, specify it here.
    #     #
    #     # gem_src: sample_site
    #     ### By default, this is not required as the action searches for a _config.yml automatically.
    #     ### However, if there are multiple Gemfiles, the action may not be able to determine which to use.
    #     ### In that case, specify the directory. (in this case, sample_site)
    #     ###
    #     ### If jekyll_src is set, the action would automatically choose the Gemfile in jekyll_src.
    #     ### In that case this input may not be needed as well.
    #     #
    #     # key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
    #     # restore-keys: ${{ runner.os }}-gems-
    #     ### In cases where you want to specify the cache key, enable the above 2 inputs
    #     ### Follows the format here https://github.com/actions/cache
    #     #
    #     # custom_opts: '--drafts --lsi'
    #     ### If you need to specify any Jekyll build options, enable the above input
    #     ### Flags accepted can be found here https://jekyllrb.com/docs/configuration/options/#build-command-options
    # - name: Build the site in the jekyll/builder container
    #   run: |
    #     docker run \
    #     -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
    #     jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: Build pages
      run: npm run build
    - name: Zip up state
      run: zip -r combined.zip ./
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist-without-markdown
        path: |
          combined.zip
    - name: Deploy to GH Pages ðŸš€
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: _site
    # - name: Run npm Start
    #   run: npm start    
